donnemartin/awesome-aws

README.md

awspec is testing framework for your AWS resources like [Serverspec](http://serverspec.org/)
example (EC2)
```ruby
describe ec2('my-ec2-tag-name') do
it { should be_running }
its(:instance_id) { should eq 'i-ec12345a' }
its(:image_id) { should eq 'ami-abc12def' }
its(:public_ip_address) { should eq '123.0.456.789' }
it { should have_security_group('my-security-group-name') }
it { should belong_to_vpc('my-vpc') }
it { should belong_to_subnet('subnet-1234a567') }
it { should have_eip('123.0.456.789') }
it { should be_disabled_api_termination }
end
```

Added awspec to DevOps section.

---

README.md

Hi,
I added a section about AWS related books. 
What do you think?

added books section

---

README.md

Kappa is a super useful tool by the legendary garnaat, and Zappa.. well, Zappa is pretty nifty too.

Adds Kappa and Zappa to Lambda lists

---

README.md

Added new link to https://github.com/mumrah/s3-multipart

s3-multipart

---

README.md

Added successor to asgard: spinnaker

Add spinnaker

---

README.md

Adding dynamodb-lambda-autoscale as an additional community project which scales dynamodb using lambda.

Add dynamodb-lambda-autoscale

---

README.md

λ Gordon is an awesome tool to create, wire and deploy AWS Lambdas using CloudFormation. It's just a thin layer of sugar around AWS services and few conventions, which makes deploying and wiring Lambdas really easy.
I've been using it for some time and I think it should be on this list.

Added λ Gordon to Lambda section

---

README.md

Additionally fix sorting for a previously added entry.

Add waynehoover/s3_direct_upload - Direct Upload to S3 With CORS

---

README.md

Add minio/minio - Object storage server compatible with S3

---

README.md

- Done that :)
Great s3 disk usage utility.
--

Add S3 Disk usage (du) utility.

---

README.md

Why is this awesome?  It helps make Rust a usable, first-class citizen in the cloud world.

Add rusoto rust sdk

---

README.md

CLI tool that allows you to create a distributed, decentralized and versioned repository.

Add s3git/s3git

---

README.md

Resiliency tool that helps applications tolerate random instance failures.

Add Netflix/chaosmonkey

---

README.md

Run your own A/B testing backend using Lambda.

Add Alephbet/gimel

---

README.md

A toolkit for developing and deploying serverless Python code in Lambda.

Add nficano/python-lambda

---

README.md

Heroku-like experience when using Lambda.

Add kubek2k/lambdoku

---

README.md

Lambda shell - Run sh commands inside the Lambda environment.

Add alestic/lambdash

---

README.md

A fast and clean way to execute Go on Lambda.

Add eawsy/aws-lambda-go

---

README.md

Deploy Node.js projects to Lambda and API Gateway easily.

Add claudiajs/claudia

---

README.md

Enterprise-strength web, mobile and event analytics, powered by Hadoop, Kafka, Kinesis, Redshift and Elasticsearch.

Add snowplow/snowplow

---

README.md

Open source tools for building custom schedulers on ECS.

Add blox/blox

---

README.md

Well, it is my book :) I put a lot of energy and effort in writing a developer-oriented introduction to AWS Lambda and serverless computing.

Add AWS Lambda in Action book

---

README.md

We working with the AWS team on a case study, and ended up deciding to do a much deeper dive on the technical aspect and post it on our blog instead.
Super in-depth review, including helpful custom animations, of the technical problems and limitations of the queue systems in general, and how Kinesis can be used to address all of these issues.
--

Add Instrumental Kinesis post as a case study

---

README.md

[Broadside](https://github.com/lumoslabs/broadside) is a tool that dramatically simplifies the deployment and configuration of ECS based containerized application.  We have been using it internally for a while and recently open sourced the tool.  [Read more in the release blog post](http://engineering.lumosity.com/amazon%20web%20services/amazon%20elastic%20compute%20cloud/amazon%20ec2%20container%20service/deploys/docker/containers/2017/01/23/broadside-is-a-tool-for-managing-ec2-containers-in-amazon-web-services/).
[Aleph](https://github.com/lumoslabs/aleph) is a full featured web application for writing, running, saving, notarizing, and doing other stuff with your redshift queries.  [Read more in the release post](http://engineering.lumosity.com/data/analytics/business%20intelligence/reds …

Broadside (ECS deploys) and Aleph (Redshift query GUI)

---

README.md

`LambStatus` is a serverless status page system. Status page system is great with the Serverless architecture, because:
* It dramatically eases the pain caused by the scaling / availability issues. It is terrible if the service is down AND heavy traffic from stuck users stops the status page.
* It reduces the infrastructure cost. A status page usually gets very low traffic and occasionally huge traffic. Pay for the traffic that the status page handles.
--

Add ks888/LambStatus - A Status Page System built on AWS Lambda

---

README.md

Sceptre offers a slick command line interface for creating and managing CloudFormation stacks. It was created at Cloudreach, making use of our eight years of experience as an AWS partner. We've used Sceptre extensively in production, and it's also been well received by the open-source community. 
--

Add sceptre/cloudreach - A CLI tool for automating CloudFormation

---

README.md

**Why is this awesome?**
[**Warrant**](https://github.com/capless/warrant) has `AWSSRP` class that is used to perform SRP (Secure Remote Password protocol) authentication. This is a preferred method of user authentication with AWS Cognito. The process involves a series of authentication challenges and responses, which if successful, results in a final response that contains ID, access and refresh token.
Python SDK boto3 lacks the support of SRP.

Add capeless/warrant - Python library for using Cognito

---

README.md

Live remote debugging in Lambda is awesome!
--

Add AWS Lambda Debugger - Remote debugging tool for Lambda functions running on Node 6.10

---

README.md

Corey Quinn writes an awesome "Last Week in AWS" email newsletter (and website:
[https://lastweekinaws.com/]( https://lastweekinaws.com/ )and its perfectly digested awesomesauce. 
--

Add Corey Quinn to Twitter users

---

README.md

A great example of how you can use CloudFormation, CodePipeline, and ECS, to create a continuous deployment flow.
--

Add ecs-refarch-continuous-deployment - Reference Architecture for creating a flexible and scalable deployment pipeline

---

README.md

awsgeek.com is a blog with notes and hand-drawn diagrams about
various AWS services by Jerry Hargrove (@awsgeek)
I'm a big fan of Jerry's hand-drawn diagrams and posts regarding various AWS services, I think his blog is awesome and that's why I'm submitting this PR.

Add awsgeek blog and twitter

---

README.md

Tool by 99designs, that allows you to securely store AWS credentials
Because it allows you to store AWS credentials on your development machine in a more secure way.

Add aws-vault - A tool for securely storing AWS credentials

---

README.md

- spin up a back-end for your mobile/web project in seconds
- utilize AWS Mobile Hub for configuration management of your backend
- update/add backend features from the cli
- instant web hosting on Amazon S3 / CloudFront
--

Add aws/awsmobile-cli - CLI for frontend devs in the JS ecosystem

---

README.md

- Display all of your AWS resources across all services (and regions) on a single web page
- Runs using Javascript SDK in local browser from a local file
- Very useful for account cleanup purposes
--

Add devops-israel/aws-inventory - Display all your resources on a single web page

---

README.md

Lambda API is a lightweight web framework for use with AWS Lambda and API Gateway. It has ZERO dependencies, is super lightweight (136KB), and was built specifically for Lambda's single run executions. It has a similar interface to ExpressJS, plus a powerful middleware system, built in logging, and binary support.

Add Lambda API - Lightweight web framework

---

README.md

Makes ECS usable by mere mortals!
--

Add stelligent/mu - CLI for creating pipelines for ECS

---

README.md

Quickly get feedback on potential security vulnerabilities in your CloudFormation tempaltes
--

Add Stelligent/cfn_nag - Static analysis of CloudFormation

---

README.md

[AthenaCLI](https://github.com/dbcli/athenacli) is a CLI tool for AWS Athena service that can do auto-completion and syntax highlighting.
A picture is worth than a thousand words.
And you can find more screenshots of the [features](https://github.com/dbcli/athenacli/blob/master/docs/features.rst) that AthenaCLI provides.

Add AthenaCLI - CLI with autocompletion and syntax highlighting

---

README.md

Updates an already existing awesome entry which is now at a different github location

Update localstack repo to newer github location

---

README.md

Add additional :fire: to lambda-api

---

README.md

An AWS driven open-source project to build a CloudFormation based on the [AWS CloudFormation Resource Specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html).
Some of the features:
- Based on the [AWS CloudFormation Resource Specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html).
- Support for [SAM](https://github.com/awslabs/serverless-application-model).
- Multipe IDE plugins available for direct feedback (e.g. VSCode, Atom, Sublime and even VIM)
- Rule based checks divided in …

Add awslabs/cfn-python-lint - CloudFormation Linter

---

README.md

Removing extra `:fire` on goadapp/goad to properly display 🔥 count.
1650 ⭐️  = 4 🔥 
--

Update score for goadapp/goad

---

README.md

Automatically generated glossary of AWS Services that is both searchable and broken down into the categories AWS use.
Provides a quick way to discover and lookup AWS services
Links go to the current documentation.
--

Add aws-glossary.info link

---

README.md

--> Because a lot of people use boto3 and need their docs to learn about it!

Update Boto3 docs link

---

.travis.yml
setup.py
tox.ini

Update Python versions

---

README.md

Updates location of Rusoto documentation from deprecated location to new location on docs.rs.

Update Rusoto documentation link.

---

README.md

The [aws-data-wrangler](https://github.com/awslabs/aws-data-wrangler) provides an easy way to send and pull data from various AWS resources using Python and Pandas.
--

Add aws-data-wrangler - Connects Pandas DataFrames and AWS data related services

---

README.md

The AWS CDK is awesome, because it brings troposphere's infrastructure-as-code spirit to other languages. Imagine your IDE helping you because it can understand all the AWS resources.
--

Add aws/aws-cdk - Framework for defining cloud infrastructure in code

---

README.md

…xy and easy to use as Dropbox.
I did read the aforementioned document and I think it is pretty in line with it.
Filestash is awesome as it makes S3 look and feel like a modern alternative to Dropbox or Google Drive. S3 is one of the supported backend and it adds on top of it a few awesome features such as shared links and full text search. 
--

Add mickael/Filestash - A modern web client for S3

---

README.md

Remove aws-glossary dead link

---

README.md

SCAR provides the benefits of AWS Lambda with the execution environment you decide, provided as a Docker image available in Docker Hub. It is probably the easiest, most convenient approach to run generic applications on AWS Lambda, as well as code in your favourite programming language, not only in those languages supported by AWS Lambda.
--

Add grycap/scar - Transparently execute containers out of Docker images in AWS Lambda

---

README.md

Want to save money? and a lot if it?
Meet [Finala](https://github.com/similarweb/finala) - resource cloud scanner that analyzes and reports wasteful and unused resources to cut unwanted expenses.
Awesome features:
- Reduce costs to a bare minimum
- Investigate unutilized resources in the UserInterface
- Define your own cloud metrics to detect unutilized resources.
- Easy installation via [Helm Chart](https://github.com/similarweb/finala-helm) on K8S
- Notify stakeholders about unutilized resources in your cloud
--

Add similarweb/finala - A cost optimization tool for the cloud

---

README.md

It generates secure least-privilege IAM Policies automagically. Writing complex IAM Policies can take place over about 30 seconds instead of hours in the IAM Visual editor / Policy Generator.
--

Add salesforce/policy_sentry - IAM Least Privilege Policy Generator

---

README.md

Can help preform security misconfigs checks before a resource is provisioned (at build time) on aws
--

Add bridgecrewio/checkov - Terraform static analysis

---

README.md

NodeJS library for single table designs.
--

Add dynamodb-onetable
