README.md
Just spotted that the Clojure SDK was described as the Haskell SDK. Presumably a copy-paste error! Love the idea behind the list, thanks for compiling it
=> Corrected typo - the Clojure SDK is a community project

README.md
Amazonka is a generated SDK and provides great, complete coverage of AWS services. The listed aws sdk has only partial coverage.
=> Update Haskell section to point to amazonka

README.md
Adds a link to Andy's Twitter account. Andy is SVP, AWS at Amazon.
=> Add Andy Jassy's Twitter account

README.md
Roadworker is a tool to manage Route53. It defines the state of Route53 using DSL, and updates Route53 according to DSL. http://roadworker.codenize.tools
=> Add winebarrel/roadworker to Route53

README.md
The cli53 (which was previously a python project) written in Go is quite useful for working with Route53 in command line. I think its worth adding in this list.
=> Add cli53 on Route53 section

README.md
> 100+ stars for community repos is not a strict requirement, it only serves as a guideline for the initial compilation. If you can vouch for the awesomeness of a repo with < 100 stars and you can explain why it should be listed, please submit a pull request.
At the moment, [StackMaster](https://github.com/envato/stack_master) has ~50 stars on GitHub. But the tool has been battle-tested to manage production stacks in our org for more than a year now. It's been a huge help to improve our productivity and collaboration among dev-ops. It has also lowered the entry barrier significantly for our devs with less ops experience to maintain AWS stacks. I really think it's an **awesome** AWS tool :)
/cc @stevehodgkiss @gstamp @patrobinson @flyinbutrs
=> Add Stack Master - A CLI tool to manage CloudFormation stacks

README.md
a Filey System for Amazon S3 written in Go
Quoting the project README: "It's a Filey System instead of a File System because goofys strives for performance first and POSIX second."
=> Add kahing/goofys - A Filey System for Amazon S3 written in Go

README.md
AutoSpotting is a tool I wrote that automatically replaces on-demand instances in existing AutoScaling groups with spot instances, using the Attach/Detach AutoScaling APIs.
Each launched spot instance may be chosen from any cheaper available instance type available on the spot market(compared to the on-demand price of the original instance), as long as it provides at least as much capacity as the original instance.
The original instances may not necessarily need to be available on the spot market, like for example t2 burstable instances could be replaced with more powerful c3.large ones, if they just happen to be the cheapest available.
For those available on the spot market it usually gives the same type or a similar one from another generation, but it can often also give larger …
=> Add cristim/autospotting

README.md
SparkleFormation and sfn are awesome tools for working with large CloudFormation managed environments.
The DSL is very light, essentially transforming a [supercharged data structure](https://github.com/chrisroberts/attribute_struct) into CloudFormation JSON templates. It supports template inheritance and nesting and supports creating reusable modules (components, dynamic, and registries) that keep large CloudFormation managed environments DRY.
The sfn command line tool makes working with templates and stacks easy and repeatable.
=> Add references to the main SparkleFormation projects

README.md
`awless` is an awesome CLI written in Go for AWS. It brings a new approach to manage virtualized infrastructures through CLI, by using `awless templates` and relies on strong foundations (RDF to model cloud resources, PEG to parse awless DSL...)
--
=> Add wallix/awless - a Powerful CLI in Go

tox.ini
Travis is now returning ERROR: py33: InterpreterNotFound: python3.3
=> Remove Python 3.3 from CI

README.md
The boto repo description links to boto/boto3 instead of boto/boto
https://github.com/boto/boto
https://github.com/boto/boto3
The author things boto3 is more awesome than boto now. 
--
=> Update boto/boto links to boto/boto3

README.md
The earlier link to AWSome Day Online Conference was old and showing 404 error. AWSome Day Online Conference is held on 31 Oct 2017, updated the link.
AWSome Day Online is awesome event for learning and hosted by AWS itself for free.
=> Fix link to AWSome Day Online Conference

README.md
AWS just released official support for Go in AWS Lambda. How cannot it be awesome?
=> Add aws/aws-lambda-go - Libraries, samples and tools to help Go developers develop Lambda functions

README.md
A good reference architecture on how to implement blue-green deployment on ECS using CloudFormation and CodePipeline.
--
=> Add ecs-blue-green-deployment - Reference architecture for doing blue green deployments on ECS

README.md
Swiss army knife for AWS CloudFormation templates - validation, conversion, generators and other various stuff.
--
=> Add Appliscale/perun - A CLI tool for linting/validation and managing CloudFormation templates and stacks.

README.md
Just updating existing line, to update repo (new org) and fire (passed 2k stars) although i also think custodian should probably also be listed in the community security repos, as its very commonly used as primary security tool (serverless policies on cwe for realtime remediation and notification), governance, and cost optimization, but not sure that fits neatly in the categories, nonetheless security seems closer then devops.
=> Update link and score for cloud-custodian

README.md
> Automatically tag AWS resources on creation, for cost assignment
Use CloudTrail and CloudWatch Events to automatically tag supported AWS resources with the creator's ARN and the create date/time. This gives users a quick way to find the age of the AWS resource and who created it.
--
=> Add GorillaStack/auto-tag - Automatically tag AWS resources on creation, for cost assignment

README.md
This is an opensource repo containing serverless architecture patterns with links to the person who created it and all their source material. Since these patterns are built in cdk they are available in TypeScript and Python but also in CloudFormation since that is what cdk uses to deploy. You do not have to use cdk to get value from this repo.
You can just clone this repo, cd into the pattern you want, install the dependencies and run the deploy task to learn. 
=> Add cdk-patterns/serverless - Deployable serverless architecture patterns built in AWS CDK

README.md
[`s5cmd`](https://github.com/peak/s5cmd) supports wide range of object management tasks both for cloud storage services and local filesystems.
* List buckets and objects
* Upload, download or delete objects
* Move, copy or rename objects
* Print object contents to stdout
* Create buckets
* Summarize objects sizes, grouping by storage class
* **Wildcard support** for all operations
* Multiple arguments support for delete operation
* **Command file support** to run commands in batches at very high execution speeds
* S3 Transfer Acceleration support
* Google Cloud Storage (and any other S3 API compatible service) support …
=> Add peak/s5cmd - Parallel S3 and local filesystem execution tool

README.md
`cognito-backup-restore` is an AIO Tool for backing up and restoring AWS Cognito User Pools
Amazon Cognito is awesome, but has its own set of limitations. Currently there is no backup option provided in case we need to take backup of users (to move to another service) or restore them to new Userpool.
`cognito-backup-restore` tries to overcome this problem by providing a way to backup users from cognito pool(s) to json file and vice-versa.
---
=> Add rahulpsd18/cognito-backup-restore - Tool for backing up and restoring Cognito user pools
